[[snippets]]
prefix = "rfc"
scope = [ "typescriptreact" ]  # language id https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers
body = 'export default function $1() {	return (	<div>$2</div>);}'
description = "next component"
